FROM abiosoft/caddy:1.0.1-no-stats

COPY conf/Caddyfile /etc/Caddyfile

RUN mkdir -p /web

COPY admin-ui/build /web/admin

COPY assets /web/static
COPY assets/favicon.ico /web/favicon.ico

RUN ls / -al
